# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  host: <%= Rails.application.secrets.db_host %>
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>


logs_development:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>



development_devlocalserver:
  <<: *default
  host: <%= Rails.application.secrets.db_host %>
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>


logs_development_devlocalserver:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>



development_elvis:
  <<: *default
  host: <%= Rails.application.secrets.db_host %>
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>


logs_development_elvis:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>


test:
  <<: *default
  host: <%= Rails.application.secrets.db_host %>
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>


logs_test:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>


devlocalserver:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

logs_devlocalserver:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>




main:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

logs_main:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>





production:
  <<: *default
  database: <%= Rails.application.secrets.db %>
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

logs_production:
  <<: *default
  host: <%= Rails.application.secrets.logs_db_host %>
  database: <%= Rails.application.secrets.logs_db %>
  username: <%= Rails.application.secrets.logs_db_user %>
  password: <%= Rails.application.secrets.logs_db_password %>

