- hosts: localhost
  gather_facts: no

  tasks:

    - name: install packages
      apt: name={{item}} state=latest
      with_items:
           - socat
           - python-pip


    - name: install pip packages
      shell: pip install {{item}}
      with_items:
           - Jinja2
           - j2cli

