- hosts: localhost
  gather_facts: no

  tasks:

    - name: download gex-aws deb
      shell: >
        wget -O /tmp/baremetal.deb https://d18ms0xu9tssc7.cloudfront.net/gex-baremetal-aws{{test}}_{{version}}.deb

    - name: install gex-aws deb
      apt:
        deb: /tmp/baremetal.deb


    - name: install bundle
      shell: gem install bundle

    - name: install gems from Gemfile
      shell: cd /home/vagrant/gexstarter/packages_install && bundle

    - name: update containers
      shell: >
        cd /home/vagrant/gexstarter/updater &&
        rake update_all_containers[{{hadoop_type}}]

    - name: install gems
      shell: >
        gem install chef &&
        gem install diplomat -v 1.3.0 &&
        gem install slack-notifier &&
        gem install parallel

    - apt_repository:
        repo: deb https://dl.bintray.com/{{gexd_repo}}/deb {{lsb_release}} main
        state: present

    - name: install gexd
      apt:
        name: "{{gexd_package}}"
        update_cache: yes
        allow_unauthenticated: yes

    - name: remove updates from cloud.cfg
      shell: sed -i '/package-update-upgrade-install/d' /etc/cloud/cloud.cfg

    - name: remove unattended upgrades
      shell: apt-get remove -y --auto-remove unattended-upgrades

    - name: stop and disable apt-daily
      shell: >
        systemctl stop apt-daily.service;
        systemctl disable apt-daily.service;
        systemctl stop apt-daily.timer;
        systemctl disable apt-daily.timer

    - name: increase threads max
      shell: >
        echo 100000 > /proc/sys/kernel/threads-max

    - name: remove apparmor
      shell: >
        sudo apt-get purge -y apparmor apparmor-utils