---
- hosts: all
#  gather_facts: no
  gather_facts: yes
  sudo: yes
#  vars_files:
#    - "vars/{{machine}}.yml"
  tasks:
    - include_vars: "../{{server}}/vars/{{machine}}.yml"
      when: machine is defined


- include: "{{script}}"
