source 'https://rubygems.org'

ruby "2.2.4"

## for sidekiq UI
#gem 'sinatra', :require => nil

# deployment
group :development do
  gem 'capistrano',  '3.4.0'
  gem 'capistrano-rails', '1.1.7'
  #gem 'capistrano-rails', '1.1.3'
  gem 'capistrano-bundler', '1.1.4'
  gem 'capistrano-rvm',   '0.1.2'

  #gem 'capistrano-passenger'
  #gem 'capistrano-touch-linked-files'
  #gem 'capistrano-upload-config'

end

