FROM studioetrange/docker-hue

RUN apt-get update;
RUN DEBIAN_FRONTEND=noninteractive  apt-get install -y apt-utils vim procps ruby openvpn curl

include(Dockerfile.common)

ADD bootstrap.sh /etc/bootstrap.sh

# Monitoring
RUN curl -fsSL https://goss.rocks/install | sh


