require_relative "../common/vagrant/utils.rb"



def provision_rabbit(config, settings, global_settings, name)


  configure_standard_box_image(config, global_settings)

  #dev.vm.network "forwarded_port", guest: 5672, host: 5672

  config.vm.define name, primary: false, autostart: false do |m|

    configure_standard_net_and_ram m, settings, global_settings


    # enable_gui(m)


    #main.vm.network "forwarded_port", guest: 5672, host: 5672
    #main.vm.network "forwarded_port", guest: 443, host: 5672

    extra_vars = {
        machine: name,
        private_ip: settings[:PRIVATE_IP],
    }


    provision_ansible m, settings, "provision", "playbook.yml", extra_vars

    provision_ansible m,  settings,"fixes", "fixes.yml", extra_vars

    provision_shell m,  "restartrabbit", "sudo service rabbitmq-server restart"


    if name == :prod
      # port redirect 443 -> 5672
      m.vm.provision "shell", run: "always", inline: "iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 5672"
      #sudo apt-get install iptables-persistent
      #sudo /etc/init.d/iptables-persistent save
      #sudo /etc/init.d/iptables-persistent reload

    end
  end

end

configure_all_boxes "provision_rabbit", RABBIT_SETTINGS
