hostname: webproxy
#domainname: webproxy.gex
domainname: webproxy.galacticexchange.io

jwt_secret: mjuRP5vfjsu6611e99

dns_server: 51.0.1.8
public_ip: 104.247.194.117

# logrotate
logrotate_files:
  - name: nginx
    filepath: /opt/openresty/nginx/logs/*.log
    user: vagrant
    group: vagrant
