#
private_ip: 51.0.10.21
hostname: devapi
domainname: devapi.gex

#
dns_server: 51.1.10.20

#
dns_hosts:
  - name: git.gex
    ip: 51.1.1.120
  - name: devdns.gex
    ip: 51.0.10.20

  - name: devsysapi.gex
    ip: 51.0.10.21
  - name: devapi.gex
    ip: 51.0.10.21
  - name: devhub.gex
    ip: 51.0.10.21

  - name: devmaster.gex
    ip: 51.0.1.32
  - name: devfiles.gex
    ip: 51.0.12.6
  - name: devrabbit.gex
    ip: 51.0.1.19
  - name: devopenvpn.gex
    ip: 51.0.1.9
  - name: devproxy.gex
    ip: 51.1.1.3
  - name: devwebproxy.gex
    ip: 51.1.1.4


# nginx
#nginx_default_server_name: devapi.gex


#
sys_domain: devapi.gex
sys_ip: 51.1.10.21
sys_port: 8000

api_domain: devapi.gex
api_ip: 51.1.10.21
api_port: 80

hub_domain: devhub.gex
hub_ip: 51.1.10.21
hub_port: 80



# apps
app_api_env: devlocalserver
app_api_name: apihub



# tests
tests_git_repo: git@dev.gex:gex/tests.git


# files
files_host: devfiles.gex
ansible_git_repo: git@dev.gex:gex/ansible.git

chef_git_repo: git@dev.gex:gex/chef-repo.git

#
ruby_user: uadmin
ruby_user_password: PH_GEX_PASSWD1
ruby_group: dev

#
ssh_keys:
  - filename: mmx.pub





# mysql
mysql_root_password: PH_GEX_PASSWD1
mysql_databases:
  - name: gex
    encoding: utf8
    collation: utf8_unicode_ci

  - name: gex_logs
    encoding: utf8
    collation: utf8_unicode_ci


mysql_users:
  - name: gex
    host: "localhost"
    password: PH_GEX_PASSWD1
    priv: "gex.*:ALL"

  - name: gex
    host: "localhost"
    password: PH_GEX_PASSWD1
    priv: "gex_logs.*:ALL"


mysql_enabled_on_startup: yes
overwrite_global_mycnf: yes
mysql_log: ""
mysql_log_error: /var/log/mysql/error.log
mysql_syslog_tag: mysqld

mysql_slow_query_log_enabled: no
mysql_slow_query_log_file: /var/log/mysql/slow.log
mysql_slow_query_time: 2


# phpredisadmin
phpredisadmin_password: PH_GEX_PASSWD1


# rabbit
rabbitmq_host: devrabbit.gex
rabbitmq_ip: 51.0.1.19
rabbitmq_user: sensu
rabbitmq_password: PH_GEX_PASSWD1




# logrotate
logrotate_files:
  - name: gex_api_log
    filepath: /var/www/apps/apihub/shared/log/*.log
    user: uadmin
    group: dev

  - name: god
    filepath: /var/www/logs/god.log
    user: uadmin
    group: dev
