require_relative "../common/vagrant/utils.rb"


def provision_proxy(config, settings, global_settings, name)


  configure_standard_box_image(config, global_settings)


  config.vm.define name, primary: false, autostart: false do |m|

    configure_standard_net_and_ram m, settings, global_settings, true
    # enable_gui(m)

    extra_vars = {
        machine: name,
        _private_ip6: settings[:PRIVATE_IP6],
        _private_ip: settings[:PRIVATE_IP],
        _public_ip: settings[:PUBLIC_IP]
    }

    provision_ansible m,  settings, "provision", "playbook.yml", extra_vars

    m.vm.provision "set_slave_route", type: "shell", run: "always", inline: "ip route replace 51.128.0.0/16 via "+ OPENVPN_SETTINGS[name.to_sym][:PRIVATE_IP]

    if name == :prod
      provision_ansible m, settings, "fixes", "fixes.yml", extra_vars

    end


  end

end


configure_all_boxes "provision_proxy", PROXY_SETTINGS
