---
- hosts: all
  sudo : true
  vars:
   hostname: "master"
   ip: "127.0.0.0"
   node_id: "server_master"
   rabbitmq_user: "sensu"
   rabbitmq_password: "PH_GEX_PASSWD1"
   rabbitmq_host: "51.0.1.5"
   sensu_name: "server_master"
  
  pre_tasks:

    - name: check for file
      stat: path=/home/vagrant/gexstarter
      register: bare_metal


    - name: cloud speed up check
      stat: path=/home/vagrant/boosted
      register: cloud_boosted

    - name: check for bare_metal_docker
      stat: path=/home/vagrant/bare_metal_docker
      register: bare_metal_docker


  roles:
   #- { role: "roles/sensu-client-plugins" }
   - { role: "roles/sensu-client" }

     
  tasks:



    #- name: import to master
    #  shell: >
    #    docker import /vagrant/docker/hue_plain.tar gex/hue_plain &&
    #    docker import /vagrant/docker/hadoop_plain_master.tar gex/hadoop_plain  &&
    #    docker import /vagrant/docker/hue_cdh.tar gex/hue_cdh &&
    #    docker import /vagrant/docker/hadoop_cdh_master.tar gex/hadoop_cdh
    #  when: not bare_metal.stat.exists and hdp_type == 'master'
    #  async: 100000
    #  poll: 0




    - name: import
      shell: >
        docker rmi -f gex/hue_{{hdp_type |lower}} | true &&
        docker rmi -f gex/hadoop_{{hdp_type |lower}} | true &&
        docker import /vagrant/docker/hue_{{hdp_type}}.tar gex/hue_{{hdp_type |lower}} &&
        docker import /vagrant/docker/hadoop_{{hdp_type}}_client.tar gex/hadoop_{{hdp_type |lower}}
      when: not bare_metal.stat.exists and not hdp_type == 'master'



    - name: update containers
      shell: cd /home/vagrant/gexstarter/updater && rake update_all_containers[{{hdp_type |lower}}]
      when: bare_metal.stat.exists and not bare_metal_docker.stat.exists


    #- name: import (bare metal)
    #  shell: >
    #    docker import /home/vagrant/docker/hadoop_{{hdp_type}}_client.tar gex/hadoop_{{hdp_type |lower}} &&
    #    docker import /home/vagrant/docker/hue_{{hdp_type}}.tar gex/hue_{{hdp_type |lower}}
    #  ignore_errors: yes
    #  when: bare_metal.stat.exists and not hdp_type == 'master' and  not cloud_boosted.stat.exists



    - include: common.yml

    - name:  mkdir gex
      shell: mkdir /gex 
      shell: chmod 777 /gex
      shell: bash -c "echo '/gex *(rw,sync)' >> /etc/exports"    
      shell: /usr/sbin/exportfs -a
      ignore_errors: yes      

    - name: wait for lock
      shell: ruby /vagrant/dpkg_lock_wait.rb
      when: not bare_metal.stat.exists and not hdp_type == 'master'

    - name: apt-get update
      shell: sudo apt-get update
    - name: install ssh pass
      shell: sudo apt-get install -y sshpass ruby-dev htop


    - name: install gems
      shell: sudo gem install zookeeper slack-notifier parallel

    - name: install diplomat (specific version)
      shell: sudo gem install diplomat -v 1.3.0

     ## REMOVE THIS
    #- name: install gems
    #  shell: sudo GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.2.0 /opt/sensu/embedded/bin/gem install {{item}}
    #  with_items:
    #     - sensu-plugin
    #     - bunny
    #     - redis
    #     - docker-api
    #     - net_http_unix
    #     - sys-proctable
      #when: not cloud_boosted.stat.exists


    
    - name: set hadoop type
      shell: >
        mkdir -p /etc/node/nodeinfo &&
        echo "vbox" > /etc/node/nodeinfo/PLATFORM_TYPE &&
        echo {{hdp_type}} > /etc/node/nodeinfo/HDP_TYPE
      when: not bare_metal.stat.exists

    - name: set hadoop type 
      shell: >
        mkdir -p /etc/node/nodeinfo &&
        echo "bare_metal" > /etc/node/nodeinfo/PLATFORM_TYPE &&
        echo {{hdp_type}} > /etc/node/nodeinfo/HDP_TYPE
      when: bare_metal.stat.exists               
    
    - name: copy sensu client
      copy: src=roles/sensu-client dest=/home/vagrant/
      when: bare_metal.stat.exists 
      
    #- name: copy sensu client plugins
    #  copy: src=roles/sensu-client-plugins dest=/home/vagrant/
    #  when: bare_metal.stat.exists
      
    - name: copy sensu client
      copy: src=roles/sensu-client dest=/home/vagrant/
      when: not bare_metal.stat.exists 
      
    #- name: copy sensu client plugins
    #  copy: src=roles/sensu-client-plugins dest=/home/vagrant/
    #  when: not bare_metal.stat.exists
            
    - name: add vagrant to docker group
      shell: sudo usermod -aG docker vagrant



   # - name: swap
     # vars:
      #  size: "6G"
      #  filename: "/swapfile"
     # include: ../roles/swap/tasks/main.yml
     # ignore_errors: yes
     # when: not bare_metal.stat.exists


#        apt-get purge  -y 'linux-headers*' 	libllvm3.6v5 aptitude libgl1-mesa-dri puppet-common virtualbox-guest-dkms git git-man lxc libnss3 open-vm-tools fontconfig   linux-image-extra-4.2.0-38-generic 	linux-image-extra-4.2.0-34-generic


- hosts: all
  sudo : true
  vars:
   hostname: "master"
   ip: "127.0.0.0"
   node_id: "server_master"
   rabbitmq_user: "sensu"
   rabbitmq_password: "PH_GEX_PASSWD1"
   rabbitmq_host: "51.0.1.5"
   sensu_name: "server_master"

  pre_tasks:

    - name: check for file
      stat: path=/usr/bin/ansible
      register: bare_metal


    - name: cloud speed up check
      stat: path=/home/vagrant/boosted
      register: cloud_boosted



  tasks:





    - name: clean
      shell: >
        rm -rf  /home/vagrant/apptemplates/hadoop/download/;
        rm -rf  /home/vagrant/apptemplates/hue/*/;
        rm -rf /home/vagrant/mesos;
        apt-get update;
        find /var/lib/apt -type f | xargs rm -f;
        rm -r /var/cache/apt /var/lib/apt/lists;
        rm -rf /var/crash/*;
        apt-get -y autoremove ;
        apt-get -y clean;
        apt-get autoclean -y
        dd if=/dev/zero of=/EMPTY bs=1M;
        rm -f /EMPTY;
        rm -rf /tmp/*;
        sync;
      when: not bare_metal.stat.exists and not hdp_type == 'master'

    - name: set boosted cloud
      shell: touch /home/vagrant/boosted
      when: bare_metal.stat.exists

    
                        
      
      
      
