---
- name: process allowed office ips allow
  template: src=hosts.allow.j2 dest=/etc/hosts.allow owner=root group=root mode=0644

- name: raise main limit
  lineinfile: >
        dest=/etc/sysctl.conf
        line="fs.file-max = 2097152" state=present

- name: raise user limits
  lineinfile: >
        dest=/etc/security/limits.conf
        line="{{ item }}" state=present
  with_items:
    - "*         hard    nofile      500000"
    - "*         soft    nofile      500000"
    - "root      hard    nofile      500000"
    - "root      soft    nofile      500000"

- name: update sysctl
  shell: sysctl -p
